# MediaWiki
version: '3'
services:
  mediawiki:
    image: mediawiki
    container_name: punk
    restart: always
    ports:
      - 8082:80
    volumes:
      - ./LocalSettings.php:/var/www/html/LocalSettings.php
      - ./images:/var/www/html/images