# MediaWiki
version: '3'
services:
  mediawiki:
    image: mediawiki
    container_name: punk
    restart: always
    ports:
      - 8082:80
    volumes:
      - ./punk_logo.png:/var/www/html/punk_logo.png
      - ./images:/var/www/html/images