# docker-compose.yml
services:
  mediawiki:
    image: mediawiki
    container_name: punk
    restart: always
    volumes:
      - ./punk_logo.png:/var/www/html/punk_logo.png
      - ./images:/var/www/html/images
      - ./LocalSettings.php:/var/www/html/LocalSettings.php
    networks:
      - interservices

networks:
  interservices:
    external: true